name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_SHA
    - name: Test docker image with root
      run: docker run -it --rm $GITHUB_REPOSITORY:$GITHUB_SHA zef list --installed
    - name: Test docker image with raku
      run: docker run -it --rm --user raku $GITHUB_REPOSITORY:$GITHUB_SHA zef list --installed
