name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_base: [alpine3.12, buster]
    env: 
      VERSION: "2020.10"
      VARIANT: ${{ matrix.image_base }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $VERSION/$VARIANT/Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_SHA
    - name: Test docker image with root
      run: docker run -it --rm $GITHUB_REPOSITORY:$GITHUB_SHA zef list --installed
    - name: Test docker image with raku
      run: docker run -it --rm --user raku $GITHUB_REPOSITORY:$GITHUB_SHA zef list --installed
